/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * One or more bounding boxes that describe the spatial extent of the dataset.
 */
export type Bbox = Array<Array<number>>
