/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Extent } from '../models/extent'
import { Keyword } from '../models/keyword'
import { Link } from '../models/link'
export interface Collection {
  /**
   * The provider of the source data for the collection.
   */
  attribution?: string

  /**
   * The list of coordinate reference systems supported by the service. The first item is the default coordinate reference system.
   */
  crs?: Array<string>

  /**
   * a description of the collection
   */
  description?: string
  extent?: Extent

  /**
   * identifier of the collection used, for example, in URIs
   */
  id: string

  /**
   * keywords about the elements in the collection
   */
  keywords?: Array<Keyword | null>
  links: Array<Link>

  /**
   * human readable title of the collection
   */
  title?: string
}
