/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Collection } from '../models/collection'
import { CollectionLink } from '../models/collection-link'
import { Link } from '../models/link'
export interface Collections {
  collections: Array<Collection & CollectionLink>
  links: Array<Link> | null
}
