/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Coordinate reference system of the coordinates in the spatial extent
 * (property `bbox`). The default reference system is WGS 84 longitude/latitude.
 */
export type Crs = string;

