/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SpatialExtent } from '../models/spatial-extent';
import { TemporalExtent } from '../models/temporal-extent';

/**
 * The extent of the collection. In the Core only spatial and temporal extents are specified. Extensions may add additional members to represent other  extents, for example, thermal or pressure ranges.
 * It is recommended that the statial extent is expected in CRS84 except if this is not possible.
 */
export interface Extent {
  spatial?: SpatialExtent;
  temporal?: TemporalExtent | null;
}
