/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeometryGeoJson } from '../models/geometry-geo-json';
import { Link } from '../models/link';
export interface FeatureJsonfg {
  conformsTo?: Array<string>;
  coordRefSys?: string;
  geometry: GeometryGeoJson | null;
  id?: (string | number);
  links?: Array<Link>;
  place: GeometryGeoJson | null;
  properties: {
} | null;
  time: any | null;
  type: 'Feature';
}
