/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeatureGeoJson } from '../models/feature-geo-json';
import { Link } from '../models/link';
import { NumberReturned } from '../models/number-returned';
import { TimeStamp } from '../models/time-stamp';
export interface FeatureCollectionGeoJson {
  features: Array<FeatureGeoJson>;
  links?: Array<Link>;
  numberReturned?: NumberReturned;
  timeStamp?: TimeStamp;
  type: 'FeatureCollection';
}
