/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeometryGeoJson } from '../models/geometry-geo-json'
import { Link } from '../models/link'
export interface FeatureGeoJson {
  bbox: Array<number> | null
  geometry: GeometryGeoJson
  id?: string | number
  links?: Array<Link>
  properties: {} | null
  type: 'Feature'
}
