/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeatureJsonfg } from '../models/feature-jsonfg'
import { Link } from '../models/link'
import { NumberReturned } from '../models/number-returned'
import { TimeStamp } from '../models/time-stamp'
export interface FeatureCollectionJsonfg {
  conformsTo?: Array<string>
  coordRefSys?: string
  features: Array<FeatureJsonfg>
  links?: Array<Link>
  numberReturned?: NumberReturned
  timeStamp?: TimeStamp
}
