/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeometrycollectionGeoJson } from '../models/geometrycollection-geo-json';
import { LinestringGeoJson } from '../models/linestring-geo-json';
import { MultilinestringGeoJson } from '../models/multilinestring-geo-json';
import { MultipointGeoJson } from '../models/multipoint-geo-json';
import { MultipolygonGeoJson } from '../models/multipolygon-geo-json';
import { PointGeoJson } from '../models/point-geo-json';
import { PolygonGeoJson } from '../models/polygon-geo-json';
export type GeometryGeoJson = (PointGeoJson | MultipointGeoJson | LinestringGeoJson | MultilinestringGeoJson | PolygonGeoJson | MultipolygonGeoJson | GeometrycollectionGeoJson);

