/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeometryGeoJson } from '../models/geometry-geo-json';
export interface GeometrycollectionGeoJson {
  geometries: Array<GeometryGeoJson>;
  type: 'GeometryCollection';
}
