/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Link } from '../models/link';
export interface LandingPage {
  description?: string;
  links: Array<Link>;
  title?: string;
}
