/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Link {
  href: string
  hreflang?: string
  length?: number
  rel: string

  /**
   * Use `true` if the `href` property contains a URI template with variables that needs to be substituted by values to get a URI
   */
  templated?: boolean
  title?: string
  type?: string

  /**
   * Without this parameter you should repeat a link for each media type the resource is offered.
   * Adding this parameter allows listing alternative media types that you can use for this resource. The value in the `type` parameter becomes the recommended media type.
   */
  types?: Array<string>
}
