/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MultipointGeoJson {
  coordinates: Array<Array<number>>;
  type: 'MultiPoint';
}
