/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MultilinestringGeoJson {
  coordinates: Array<Array<Array<number>>>
  type: 'MultiLineString'
}
