/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * The number of elements in the collection.
 *
 * A server may omit this information in a response, if the information
 * about the number of elements is not known or difficult to compute.
 *
 * If the value is provided, the value shall be identical to the number
 * of items in the returned array.
 */
export type NumberReturned = number
