/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Bbox } from '../models/bbox'
import { Crs } from '../models/crs'

/**
 * The spatial extent of the element in the collection.
 */
export interface SpatialExtent {
  bbox: Bbox
  crs?: Crs
}
