/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * One or more time intervals that describe the temporal extent of the dataset.
 * The value `null` is supported and indicates an open time intervall.
 * In the Core only a single time interval is supported. Extensions may support
 * multiple intervals. If multiple intervals are provided, the union of the
 * intervals describes the temporal extent.
 */
export type TemporalInterval = Array<Array<string | null>>;
