/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TemporalInterval } from '../models/temporal-interval'
import { Trs } from '../models/trs'

/**
 * The temporal extent of the element in the collection.
 */
export type TemporalExtent = {
  interval?: TemporalInterval | null
  trs?: Trs
}
