/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * This property indicates the time and date when the response was generated.
 */
export type TimeStamp = string;
