/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Trs } from './trs'

/**
 * Each possible value of `Trs`
 */
export const TRS: Trs[] = ['http://www.opengis.net/def/uom/ISO-8601/0/Gregorian']
