/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Coordinate reference system of the coordinates in the temporal extent
 * (property `interval`). The default reference system is the Gregorian calendar.
 * In the Core this is the only supported temporal reference system.
 * Extensions may support additional temporal reference systems and add
 * additional enum values.
 */
export enum Trs {
  HttpWwwOpengisNetDefUomIso86010Gregorian = 'http://www.opengis.net/def/uom/ISO-8601/0/Gregorian'
}
