/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Keyword } from './keyword'
import { Extent } from './extent'
import { Link } from './link'

export interface Collection {
  /**
   * The provider of the source data for the collection.
   */
  attribution?: string
  /**
   * The list of coordinate reference systems supported by the service. The first item is the default coordinate reference system.
   */
  crs?: Array<string>
  /**
   * a description of the collection
   */
  description?: string
  extent?: Extent
  /**
   * identifier of the collection used, for example, in URIs
   */
  id: string
  /**
   * keywords about the elements in the collection
   */
  keywords?: Array<Keyword>
  links: Array<Link>
  /**
   * human readable title of the collection
   */
  title?: string
}
