/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionsCollectionsInner } from './collectionsCollectionsInner'
import { Link } from './link'

export interface Collections {
  collections: Array<CollectionsCollectionsInner>
  links: Array<Link> | null
}
