/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * JSON schema for exceptions based on RFC 7807
 */
export interface Exception {
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
   */
  instance?: string
  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status?: number
  /**
   * A short, human-readable summary of the problem type.
   */
  title: string
  /**
   * A URI reference that identifies the problem type.
   */
  type?: string
}
