/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TemporalExtent } from './temporalExtent'
import { SpatialExtent } from './spatialExtent'

/**
 * The extent of the collection. In the Core only spatial and temporal extents are specified. Extensions may add additional members to represent other  extents, for example, thermal or pressure ranges. It is recommended that the statial extent is expected in CRS84 except if this is not possible.
 */
export interface Extent {
  spatial?: SpatialExtent
  temporal?: TemporalExtent | null
}
