/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeometryGeoJSON } from './geometryGeoJSON'
import { FeatureGeoJSONId } from './featureGeoJSONId'
import { Link } from './link'

export interface FeatureJSONFG {
  bbox: Array<number> | null
  conformsTo?: Array<string>
  coordRefSys?: string
  geometry: GeometryGeoJSON | null
  id?: FeatureGeoJSONId
  links?: Array<Link>
  place: GeometryGeoJSON | null
  properties: object | null
  time: any | null
  type: FeatureJSONFG.TypeEnum
}
export namespace FeatureJSONFG {
  export type TypeEnum = 'Feature'
  export const TypeEnum = {
    Feature: 'Feature' as TypeEnum,
  }
}
