/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeatureGeoJSON } from './featureGeoJSON'
import { Link } from './link'

export interface FeatureCollectionGeoJSON {
  features: Array<FeatureGeoJSON>
  links?: Array<Link>
  /**
   * The number of elements in the collection.  A server may omit this information in a response, if the information about the number of elements is not known or difficult to compute.  If the value is provided, the value shall be identical to the number of items in the returned array.
   */
  numberReturned?: number
  /**
   * This property indicates the time and date when the response was generated.
   */
  timeStamp?: string
  type: FeatureCollectionGeoJSON.TypeEnum
}
export namespace FeatureCollectionGeoJSON {
  export type TypeEnum = 'FeatureCollection'
  export const TypeEnum = {
    FeatureCollection: 'FeatureCollection' as TypeEnum,
  }
}
