/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeatureJSONFG } from './featureJSONFG'
import { Link } from './link'

export interface FeatureCollectionJSONFG {
  conformsTo?: Array<string>
  coordRefSys?: string
  features: Array<FeatureJSONFG>
  links?: Array<Link>
  /**
   * The number of elements in the collection.  A server may omit this information in a response, if the information about the number of elements is not known or difficult to compute.  If the value is provided, the value shall be identical to the number of items in the returned array.
   */
  numberReturned?: number
  /**
   * This property indicates the time and date when the response was generated.
   */
  timeStamp?: string
}
