/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeometryGeoJSON } from './geometryGeoJSON'
import { FeatureGeoJSONId } from './featureGeoJSONId'
import { Link } from './link'

export interface FeatureGeoJSON {
  bbox: Array<number> | null
  geometry: GeometryGeoJSON
  id?: FeatureGeoJSONId
  links?: Array<Link>
  properties: object | null
  type: FeatureGeoJSON.TypeEnum
}
export namespace FeatureGeoJSON {
  export type TypeEnum = 'Feature'
  export const TypeEnum = {
    Feature: 'Feature' as TypeEnum,
  }
}
