/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeometryGeoJSON } from './geometryGeoJSON'

export interface GeometrycollectionGeoJSON {
  geometries: Array<GeometryGeoJSON>
  type: GeometrycollectionGeoJSON.TypeEnum
}
export namespace GeometrycollectionGeoJSON {
  export type TypeEnum = 'GeometryCollection'
  export const TypeEnum = {
    GeometryCollection: 'GeometryCollection' as TypeEnum,
  }
}
