/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultipolygonGeoJSON } from './multipolygonGeoJSON'
import { GeometrycollectionGeoJSON } from './geometrycollectionGeoJSON'
import { MultilinestringGeoJSON } from './multilinestringGeoJSON'
import { MultipointGeoJSON } from './multipointGeoJSON'
import { PointGeoJSON } from './pointGeoJSON'
import { PolygonGeoJSON } from './polygonGeoJSON'
import { LinestringGeoJSON } from './linestringGeoJSON'

/**
 * @type GeometryGeoJSON
 * @export
 */
export type GeometryGeoJSON =
  | GeometrycollectionGeoJSON
  | LinestringGeoJSON
  | MultilinestringGeoJSON
  | MultipointGeoJSON
  | MultipolygonGeoJSON
  | PointGeoJSON
  | PolygonGeoJSON
