/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link'

/**
 * Reusable object that contains an id to a resource and links where the object is described or a representation retrieved. Typically it is useful for paths like `\\resources` and `\\resources\\{resourceId}`.   `\\resources` will respond an array of id-link listing the `resourceId` and the links to get it. \\collections and \\collections\\{collectionId} is an exception to this pattern. The fact that `links` is an array can be used to advertise the same object representation in different formats.
 */
export interface IdLink {
  id: string
  links: Array<Link>
  title?: string
}
