/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LinestringGeoJSON {
  coordinates: Array<Array<number>>
  type: LinestringGeoJSON.TypeEnum
}
export namespace LinestringGeoJSON {
  export type TypeEnum = 'LineString'
  export const TypeEnum = {
    LineString: 'LineString' as TypeEnum,
  }
}
