/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MultilinestringGeoJSON {
  coordinates: Array<Array<Array<number>>>
  type: MultilinestringGeoJSON.TypeEnum
}
export namespace MultilinestringGeoJSON {
  export type TypeEnum = 'MultiLineString'
  export const TypeEnum = {
    MultiLineString: 'MultiLineString' as TypeEnum,
  }
}
