/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MultipointGeoJSON {
  coordinates: Array<Array<number>>
  type: MultipointGeoJSON.TypeEnum
}
export namespace MultipointGeoJSON {
  export type TypeEnum = 'MultiPoint'
  export const TypeEnum = {
    MultiPoint: 'MultiPoint' as TypeEnum,
  }
}
