/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MultipolygonGeoJSON {
  coordinates: Array<Array<Array<Array<number>>>>
  type: MultipolygonGeoJSON.TypeEnum
}
export namespace MultipolygonGeoJSON {
  export type TypeEnum = 'MultiPolygon'
  export const TypeEnum = {
    MultiPolygon: 'MultiPolygon' as TypeEnum,
  }
}
