/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PointGeoJSON {
  coordinates: Array<number>
  type: PointGeoJSON.TypeEnum
}
export namespace PointGeoJSON {
  export type TypeEnum = 'Point'
  export const TypeEnum = {
    Point: 'Point' as TypeEnum,
  }
}
