/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PolygonGeoJSON {
  coordinates: Array<Array<Array<number>>>
  type: PolygonGeoJSON.TypeEnum
}
export namespace PolygonGeoJSON {
  export type TypeEnum = 'Polygon'
  export const TypeEnum = {
    Polygon: 'Polygon' as TypeEnum,
  }
}
