/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SearchLigplaatsParameter {
  /**
   * The relevance score of the ligplaats collection.
   */
  relevance?: number
  /**
   * The version of the ligplaats collection.
   */
  version: number
}
