/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The spatial extent of the element in the collection.
 */
export interface SpatialExtent {
  /**
   * One or more bounding boxes that describe the spatial extent of the dataset.
   */
  bbox: Array<Array<number>>
  /**
   * Coordinate reference system of the coordinates in the spatial extent (property `bbox`). The default reference system is WGS 84 longitude/latitude.
   */
  crs?: string
}
