/**
 * PDOK Location API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Trs } from './trs'

/**
 * The temporal extent of the element in the collection.
 */
export interface TemporalExtent {
  /**
   * One or more time intervals that describe the temporal extent of the dataset. The value `null` is supported and indicates an open time intervall. In the Core only a single time interval is supported. Extensions may support multiple intervals. If multiple intervals are provided, the union of the intervals describes the temporal extent.
   */
  interval?: Array<Array<string | null>> | null
  trs?: Trs
}
export namespace TemporalExtent {}
