/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { RequestBuilder } from '../../request-builder'

export interface GetConformanceDeclaration$Html$Params {
  /**
   * The optional f parameter indicates the output format that the server shall provide as part of the response document.  The default format is JSON.
   */
  f?: 'json' | 'html'
}

export function getConformanceDeclaration$Html(
  http: HttpClient,
  rootUrl: string,
  params?: GetConformanceDeclaration$Html$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, getConformanceDeclaration$Html.PATH, 'get')
  if (params) {
    rb.query('f', params.f, { style: 'form', explode: false })
  }

  return http.request(rb.build({ responseType: 'text', accept: 'text/html', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>
    })
  )
}

getConformanceDeclaration$Html.PATH = '/conformance'
