/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LandingPage } from '../../models/landing-page';

export interface GetLandingPage$Json$Params {

/**
 * The optional f parameter indicates the output format that the server shall provide as part of the response document.  The default format is JSON.
 */
  f?: 'json' | 'html';
}

export function getLandingPage$Json(http: HttpClient, rootUrl: string, params?: GetLandingPage$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<LandingPage>> {
  const rb = new RequestBuilder(rootUrl, getLandingPage$Json.PATH, 'get');
  if (params) {
    rb.query('f', params.f, {"style":"form","explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LandingPage>;
    })
  );
}

getLandingPage$Json.PATH = '/';
