//go:generate ../../../../hack/generate-cql-parser.sh
package cql

import (
	"github.com/PDOK/gokoala/internal/ogc/features/cql/parser"
	"github.com/antlr4-go/antlr/v4"
)

// Listener converts OGC CQL2 Text to SQL.
type Listener interface {
	parser.CqlParserListener

	// GetSQL returns the SQL generated by the listener.
	GetSQL() string
}

// ParseToSQL parses OGC CQL2 Text to SQL.
func ParseToSQL(cql string, listener Listener) string {
	if cql == "" {
		return ""
	}
	input := antlr.NewInputStream(cql)

	// lexer
	cqlLexer := parser.NewCqlLexer(input)
	cqlLexer.RemoveErrorListeners()
	cqlLexer.AddErrorListener(antlr.NewConsoleErrorListener()) // Print errors, TODO: replace with proper error handling
	tokens := antlr.NewCommonTokenStream(cqlLexer, antlr.TokenDefaultChannel)

	// parser
	cqlParser := parser.NewCqlParser(tokens)
	cqlParser.RemoveErrorListeners()
	cqlParser.AddErrorListener(antlr.NewConsoleErrorListener()) // Print errors, TODO: replace with proper error handling
	tree := cqlParser.CqlFilter()

	// walker (walks the parse tree and calls the listener)
	antlr.ParseTreeWalkerDefault.Walk(listener, tree)

	return listener.GetSQL()
}
