//go:generate ../../../../hack/generate-cql-parser.sh
package cql

import (
	"errors"
	"fmt"

	"github.com/PDOK/gokoala/internal/engine/types"
	"github.com/PDOK/gokoala/internal/ogc/features/cql/parser"
	"github.com/antlr4-go/antlr/v4"
)

var errInvalidCharsInCQL = errors.New("invalid characters in CQL filter")

// ParseToSQL parses OGC CQL2 Text to SQL, as described in OGC API Features - Part 3.
// Spec: https://docs.ogc.org/is/21-065r2/21-065r2.html
func ParseToSQL(cql string, listener Listener) (*SQLResult, error) {
	if cql == "" {
		return nil, nil
	}
	if !types.IsValidString(cql) {
		return nil, errInvalidCharsInCQL
	}

	errorListener := newErrorListener()

	// lexer
	cqlLexer := parser.NewCqlLexer(antlr.NewInputStream(cql))
	cqlLexer.RemoveErrorListeners()
	cqlLexer.AddErrorListener(errorListener)
	tokens := antlr.NewCommonTokenStream(cqlLexer, antlr.TokenDefaultChannel)

	// parser
	cqlParser := parser.NewCqlParser(tokens)
	cqlParser.RemoveErrorListeners()
	cqlParser.AddErrorListener(errorListener)
	tree := cqlParser.CqlFilter()

	// walker (walks the parse tree and calls our listener)
	listener.AddErrorListener(errorListener)
	antlr.ParseTreeWalkerDefault.Walk(listener, tree)

	// result
	return listener.GetResult(), errorListener.Summary()
}

// Listener converts OGC CQL2 Text parse tree to SQL.
type Listener interface {
	parser.CqlParserListener

	AddErrorListener(errorListener *ErrorListener)

	// GetResult returns the SQL and parameters generated by the listener.
	GetResult() *SQLResult
}

// ErrorListener custom ANTLR error listener. Used to collect parse errors and return them as a single error.
type ErrorListener struct {
	*antlr.DefaultErrorListener

	// list of errors encountered during all stages of parsing (lexing, parsing, walking).
	parseErrors []error
}

func newErrorListener() *ErrorListener {
	return &ErrorListener{antlr.NewDefaultErrorListener(), make([]error, 0)}
}

// SyntaxError is called by ANTLR when a syntax error occurs.
func (c *ErrorListener) SyntaxError(_ antlr.Recognizer, _ any, _, column int, msg string, _ antlr.RecognitionException) {
	c.parseErrors = append(c.parseErrors, fmt.Errorf("syntax error at column %d: %s", column, msg))
}

// Error is called by our own CQL-to-SQL listeners when an error occurs.
func (c *ErrorListener) Error(msg string) {
	c.parseErrors = append(c.parseErrors, fmt.Errorf("error: %s", msg))
}

// Summary returns a single error containing all encountered errors.
func (c *ErrorListener) Summary() error {
	err := errors.Join(c.parseErrors...)
	if err != nil {
		return fmt.Errorf("failed to parse CQL filter:\n%w", err)
	}
	return nil
}

type SQLResult struct {
	// SQL is the SQL string generated by the listener.
	SQL string

	// Params are the named parameters generated by the listener.
	Params map[string]any

	// RtreeSQL is a SQL string to include the R-Tree index. This only applies to GeoPackage datasources.
	RtreeSQL string
}
