//go:generate ../../../../hack/generate-cql-parser.sh
package cql

import (
	"github.com/PDOK/gokoala/internal/ogc/features/cql/parser"
	"github.com/antlr4-go/antlr/v4"
)

// Listener converts OGC CQL2 Text to SQL.
type Listener interface {
	parser.CqlParserListener

	// GetSQL returns the SQL generated by the listener.
	GetSQL() (string, map[string]any)
}

// ParseToSQL parses OGC CQL2 Text to SQL, as described in OGC API Features - Part 3.
func ParseToSQL(cql string, listener Listener) (string, map[string]any, error) {
	if cql == "" {
		return "", nil, nil
	}
	input := antlr.NewInputStream(cql)

	// lexer
	cqlLexer := parser.NewCqlLexer(input)
	cqlLexer.RemoveErrorListeners()
	cqlLexer.AddErrorListener(antlr.NewConsoleErrorListener()) // Print errors, TODO: replace with proper error handling
	tokens := antlr.NewCommonTokenStream(cqlLexer, antlr.TokenDefaultChannel)

	// parser
	cqlParser := parser.NewCqlParser(tokens)
	cqlParser.RemoveErrorListeners()
	cqlParser.AddErrorListener(antlr.NewConsoleErrorListener()) // Print errors, TODO: replace with proper error handling
	tree := cqlParser.CqlFilter()

	// walker (walks the parse tree and calls the listener)
	antlr.ParseTreeWalkerDefault.Walk(listener, tree)

	sql, namedParams := listener.GetSQL()
	return sql, namedParams, nil
}
