package cql

import (
	"log"

	"github.com/PDOK/gokoala/internal/engine/types"
	"github.com/PDOK/gokoala/internal/ogc/features/cql/parser"
	"github.com/antlr4-go/antlr/v4"
)

// PostgresListener converts OGC CQL2 Text to PostgreSQL-compatible SQL.
type PostgresListener struct {
	*parser.BaseCqlParserListener

	stack *types.Stack
}

func NewPostgresListener() *PostgresListener {
	return &PostgresListener{
		stack: types.NewStack(),
	}
}

// GetSQL returns the final SQL string generated by the listener.
func (l *PostgresListener) GetSQL() string {
	return l.stack.Peek()
}

func (l *PostgresListener) ExitEveryRule(_ antlr.ParserRuleContext) {
	log.Println("WARNING: CQL parser for Postgres isn't yet implemented")
}
