package cql

import (
	"log"

	"github.com/PDOK/gokoala/internal/engine/types"
	"github.com/PDOK/gokoala/internal/engine/util"
	"github.com/PDOK/gokoala/internal/ogc/features/domain"
	"github.com/antlr4-go/antlr/v4"
)

// PostgresListener converts OGC CQL2 Text to PostgreSQL-compatible SQL.
type PostgresListener struct {
	*CommonListener
}

func NewPostgresListener(randomizer util.Randomizer, queryables []domain.Field, srid domain.SRID) *PostgresListener {
	return &PostgresListener{&CommonListener{
		stack:       types.NewStack(),
		namedParams: make(map[string]any),
		srid:        srid,
		randomizer:  randomizer,
		queryables:  queryables,
	}}
}

// GetResult returns the final SQL string generated by the listener.
func (l *PostgresListener) GetResult() *SQLResult {
	return &SQLResult{SQL: l.stack.Peek(), Params: l.namedParams}
}

func (l *PostgresListener) ExitEveryRule(_ antlr.ParserRuleContext) {
	log.Println("WARNING: CQL parser for Postgres isn't yet implemented")
}
