//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package config

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalDatasource) DeepCopyInto(out *AdditionalDatasource) {
	*out = *in
	in.Datasource.DeepCopyInto(&out.Datasource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalDatasource.
func (in *AdditionalDatasource) DeepCopy() *AdditionalDatasource {
	if in == nil {
		return nil
	}
	out := new(AdditionalDatasource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionEntry3dGeoVolumes) DeepCopyInto(out *CollectionEntry3dGeoVolumes) {
	*out = *in
	if in.TileServerPath != nil {
		in, out := &in.TileServerPath, &out.TileServerPath
		*out = new(string)
		**out = **in
	}
	if in.URITemplate3dTiles != nil {
		in, out := &in.URITemplate3dTiles, &out.URITemplate3dTiles
		*out = new(string)
		**out = **in
	}
	if in.URITemplateImplicitTilingSubtree != nil {
		in, out := &in.URITemplateImplicitTilingSubtree, &out.URITemplateImplicitTilingSubtree
		*out = new(string)
		**out = **in
	}
	if in.URITemplateDTM != nil {
		in, out := &in.URITemplateDTM, &out.URITemplateDTM
		*out = new(string)
		**out = **in
	}
	if in.URL3DViewer != nil {
		in, out := &in.URL3DViewer, &out.URL3DViewer
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionEntry3dGeoVolumes.
func (in *CollectionEntry3dGeoVolumes) DeepCopy() *CollectionEntry3dGeoVolumes {
	if in == nil {
		return nil
	}
	out := new(CollectionEntry3dGeoVolumes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionEntryFeatures) DeepCopyInto(out *CollectionEntryFeatures) {
	*out = *in
	if in.TableName != nil {
		in, out := &in.TableName, &out.TableName
		*out = new(string)
		**out = **in
	}
	if in.Datasources != nil {
		in, out := &in.Datasources, &out.Datasources
		*out = new(Datasources)
		(*in).DeepCopyInto(*out)
	}
	in.Filters.DeepCopyInto(&out.Filters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionEntryFeatures.
func (in *CollectionEntryFeatures) DeepCopy() *CollectionEntryFeatures {
	if in == nil {
		return nil
	}
	out := new(CollectionEntryFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionEntryTiles) DeepCopyInto(out *CollectionEntryTiles) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionEntryTiles.
func (in *CollectionEntryTiles) DeepCopy() *CollectionEntryTiles {
	if in == nil {
		return nil
	}
	out := new(CollectionEntryTiles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	in.License.DeepCopyInto(&out.License)
	in.BaseURL.DeepCopyInto(&out.BaseURL)
	in.DatasetCatalogURL.DeepCopyInto(&out.DatasetCatalogURL)
	if in.AvailableLanguages != nil {
		in, out := &in.AvailableLanguages, &out.AvailableLanguages
		*out = make([]Language, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.OgcAPI.DeepCopyInto(&out.OgcAPI)
	if in.Thumbnail != nil {
		in, out := &in.Thumbnail, &out.Thumbnail
		*out = new(string)
		**out = **in
	}
	if in.Keywords != nil {
		in, out := &in.Keywords, &out.Keywords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.Support != nil {
		in, out := &in.Support, &out.Support
		*out = new(Support)
		(*in).DeepCopyInto(*out)
	}
	if in.DatasetDetails != nil {
		in, out := &in.DatasetDetails, &out.DatasetDetails
		*out = make([]DatasetDetail, len(*in))
		copy(*out, *in)
	}
	in.DatasetMetadata.DeepCopyInto(&out.DatasetMetadata)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resources)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetDetail) DeepCopyInto(out *DatasetDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetDetail.
func (in *DatasetDetail) DeepCopy() *DatasetDetail {
	if in == nil {
		return nil
	}
	out := new(DatasetDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetMetadata) DeepCopyInto(out *DatasetMetadata) {
	*out = *in
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = new(string)
		**out = **in
	}
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetMetadata.
func (in *DatasetMetadata) DeepCopy() *DatasetMetadata {
	if in == nil {
		return nil
	}
	out := new(DatasetMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Datasource) DeepCopyInto(out *Datasource) {
	*out = *in
	if in.GeoPackage != nil {
		in, out := &in.GeoPackage, &out.GeoPackage
		*out = new(GeoPackage)
		(*in).DeepCopyInto(*out)
	}
	if in.PostGIS != nil {
		in, out := &in.PostGIS, &out.PostGIS
		*out = new(PostGIS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Datasource.
func (in *Datasource) DeepCopy() *Datasource {
	if in == nil {
		return nil
	}
	out := new(Datasource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Datasources) DeepCopyInto(out *Datasources) {
	*out = *in
	in.DefaultWGS84.DeepCopyInto(&out.DefaultWGS84)
	if in.Additional != nil {
		in, out := &in.Additional, &out.Additional
		*out = make([]AdditionalDatasource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Datasources.
func (in *Datasources) DeepCopy() *Datasources {
	if in == nil {
		return nil
	}
	out := new(Datasources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extent) DeepCopyInto(out *Extent) {
	*out = *in
	if in.Bbox != nil {
		in, out := &in.Bbox, &out.Bbox
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extent.
func (in *Extent) DeepCopy() *Extent {
	if in == nil {
		return nil
	}
	out := new(Extent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeatureFilters) DeepCopyInto(out *FeatureFilters) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]PropertyFilter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureFilters.
func (in *FeatureFilters) DeepCopy() *FeatureFilters {
	if in == nil {
		return nil
	}
	out := new(FeatureFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoPackage) DeepCopyInto(out *GeoPackage) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(GeoPackageLocal)
		**out = **in
	}
	if in.Cloud != nil {
		in, out := &in.Cloud, &out.Cloud
		*out = new(GeoPackageCloud)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoPackage.
func (in *GeoPackage) DeepCopy() *GeoPackage {
	if in == nil {
		return nil
	}
	out := new(GeoPackage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoPackageCloud) DeepCopyInto(out *GeoPackageCloud) {
	*out = *in
	out.GeoPackageCommon = in.GeoPackageCommon
	in.Cache.DeepCopyInto(&out.Cache)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoPackageCloud.
func (in *GeoPackageCloud) DeepCopy() *GeoPackageCloud {
	if in == nil {
		return nil
	}
	out := new(GeoPackageCloud)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoPackageCloudCache) DeepCopyInto(out *GeoPackageCloudCache) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoPackageCloudCache.
func (in *GeoPackageCloudCache) DeepCopy() *GeoPackageCloudCache {
	if in == nil {
		return nil
	}
	out := new(GeoPackageCloudCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoPackageCommon) DeepCopyInto(out *GeoPackageCommon) {
	*out = *in
	in.QueryTimeout.DeepCopyInto(&out.QueryTimeout)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoPackageCommon.
func (in *GeoPackageCommon) DeepCopy() *GeoPackageCommon {
	if in == nil {
		return nil
	}
	out := new(GeoPackageCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoPackageLocal) DeepCopyInto(out *GeoPackageLocal) {
	*out = *in
	out.GeoPackageCommon = in.GeoPackageCommon
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoPackageLocal.
func (in *GeoPackageLocal) DeepCopy() *GeoPackageLocal {
	if in == nil {
		return nil
	}
	out := new(GeoPackageLocal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoSpatialCollection) DeepCopyInto(out *GeoSpatialCollection) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(GeoSpatialCollectionMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.GeoVolumes != nil {
		in, out := &in.GeoVolumes, &out.GeoVolumes
		*out = new(CollectionEntry3dGeoVolumes)
		(*in).DeepCopyInto(*out)
	}
	if in.Tiles != nil {
		in, out := &in.Tiles, &out.Tiles
		*out = new(CollectionEntryTiles)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(CollectionEntryFeatures)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoSpatialCollection.
func (in *GeoSpatialCollection) DeepCopy() *GeoSpatialCollection {
	if in == nil {
		return nil
	}
	out := new(GeoSpatialCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoSpatialCollectionMetadata) DeepCopyInto(out *GeoSpatialCollectionMetadata) {
	*out = *in
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Thumbnail != nil {
		in, out := &in.Thumbnail, &out.Thumbnail
		*out = new(string)
		**out = **in
	}
	if in.Keywords != nil {
		in, out := &in.Keywords, &out.Keywords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.TemporalProperties != nil {
		in, out := &in.TemporalProperties, &out.TemporalProperties
		*out = new(TemporalProperties)
		**out = **in
	}
	if in.Extent != nil {
		in, out := &in.Extent, &out.Extent
		*out = new(Extent)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageCrs != nil {
		in, out := &in.StorageCrs, &out.StorageCrs
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoSpatialCollectionMetadata.
func (in *GeoSpatialCollectionMetadata) DeepCopy() *GeoSpatialCollectionMetadata {
	if in == nil {
		return nil
	}
	out := new(GeoSpatialCollectionMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *License) DeepCopyInto(out *License) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new License.
func (in *License) DeepCopy() *License {
	if in == nil {
		return nil
	}
	out := new(License)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Limit) DeepCopyInto(out *Limit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Limit.
func (in *Limit) DeepCopy() *Limit {
	if in == nil {
		return nil
	}
	out := new(Limit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OgcAPI) DeepCopyInto(out *OgcAPI) {
	*out = *in
	if in.GeoVolumes != nil {
		in, out := &in.GeoVolumes, &out.GeoVolumes
		*out = new(OgcAPI3dGeoVolumes)
		(*in).DeepCopyInto(*out)
	}
	if in.Tiles != nil {
		in, out := &in.Tiles, &out.Tiles
		*out = new(OgcAPITiles)
		(*in).DeepCopyInto(*out)
	}
	if in.Styles != nil {
		in, out := &in.Styles, &out.Styles
		*out = new(OgcAPIStyles)
		(*in).DeepCopyInto(*out)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(OgcAPIFeatures)
		(*in).DeepCopyInto(*out)
	}
	if in.Processes != nil {
		in, out := &in.Processes, &out.Processes
		*out = new(OgcAPIProcesses)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OgcAPI.
func (in *OgcAPI) DeepCopy() *OgcAPI {
	if in == nil {
		return nil
	}
	out := new(OgcAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OgcAPI3dGeoVolumes) DeepCopyInto(out *OgcAPI3dGeoVolumes) {
	*out = *in
	in.TileServer.DeepCopyInto(&out.TileServer)
	if in.Collections != nil {
		in, out := &in.Collections, &out.Collections
		*out = make(GeoSpatialCollections, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OgcAPI3dGeoVolumes.
func (in *OgcAPI3dGeoVolumes) DeepCopy() *OgcAPI3dGeoVolumes {
	if in == nil {
		return nil
	}
	out := new(OgcAPI3dGeoVolumes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OgcAPIFeatures) DeepCopyInto(out *OgcAPIFeatures) {
	*out = *in
	if in.Collections != nil {
		in, out := &in.Collections, &out.Collections
		*out = make(GeoSpatialCollections, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Limit = in.Limit
	if in.Datasources != nil {
		in, out := &in.Datasources, &out.Datasources
		*out = new(Datasources)
		(*in).DeepCopyInto(*out)
	}
	if in.ValidateResponses != nil {
		in, out := &in.ValidateResponses, &out.ValidateResponses
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OgcAPIFeatures.
func (in *OgcAPIFeatures) DeepCopy() *OgcAPIFeatures {
	if in == nil {
		return nil
	}
	out := new(OgcAPIFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OgcAPIProcesses) DeepCopyInto(out *OgcAPIProcesses) {
	*out = *in
	in.ProcessesServer.DeepCopyInto(&out.ProcessesServer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OgcAPIProcesses.
func (in *OgcAPIProcesses) DeepCopy() *OgcAPIProcesses {
	if in == nil {
		return nil
	}
	out := new(OgcAPIProcesses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OgcAPIStyles) DeepCopyInto(out *OgcAPIStyles) {
	*out = *in
	if in.SupportedStyles != nil {
		in, out := &in.SupportedStyles, &out.SupportedStyles
		*out = make([]Style, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OgcAPIStyles.
func (in *OgcAPIStyles) DeepCopy() *OgcAPIStyles {
	if in == nil {
		return nil
	}
	out := new(OgcAPIStyles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OgcAPITiles) DeepCopyInto(out *OgcAPITiles) {
	*out = *in
	in.TileServer.DeepCopyInto(&out.TileServer)
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SupportedSrs != nil {
		in, out := &in.SupportedSrs, &out.SupportedSrs
		*out = make([]SupportedSrs, len(*in))
		copy(*out, *in)
	}
	if in.URITemplateTiles != nil {
		in, out := &in.URITemplateTiles, &out.URITemplateTiles
		*out = new(string)
		**out = **in
	}
	if in.Collections != nil {
		in, out := &in.Collections, &out.Collections
		*out = make(GeoSpatialCollections, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OgcAPITiles.
func (in *OgcAPITiles) DeepCopy() *OgcAPITiles {
	if in == nil {
		return nil
	}
	out := new(OgcAPITiles)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostGIS) DeepCopyInto(out *PostGIS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostGIS.
func (in *PostGIS) DeepCopy() *PostGIS {
	if in == nil {
		return nil
	}
	out := new(PostGIS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyFilter) DeepCopyInto(out *PropertyFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyFilter.
func (in *PropertyFilter) DeepCopy() *PropertyFilter {
	if in == nil {
		return nil
	}
	out := new(PropertyFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Style) DeepCopyInto(out *Style) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Keywords != nil {
		in, out := &in.Keywords, &out.Keywords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Thumbnail != nil {
		in, out := &in.Thumbnail, &out.Thumbnail
		*out = new(string)
		**out = **in
	}
	if in.Formats != nil {
		in, out := &in.Formats, &out.Formats
		*out = make([]StyleFormat, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Style.
func (in *Style) DeepCopy() *Style {
	if in == nil {
		return nil
	}
	out := new(Style)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StyleFormat) DeepCopyInto(out *StyleFormat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StyleFormat.
func (in *StyleFormat) DeepCopy() *StyleFormat {
	if in == nil {
		return nil
	}
	out := new(StyleFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Support) DeepCopyInto(out *Support) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Support.
func (in *Support) DeepCopy() *Support {
	if in == nil {
		return nil
	}
	out := new(Support)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportedSrs) DeepCopyInto(out *SupportedSrs) {
	*out = *in
	out.ZoomLevelRange = in.ZoomLevelRange
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportedSrs.
func (in *SupportedSrs) DeepCopy() *SupportedSrs {
	if in == nil {
		return nil
	}
	out := new(SupportedSrs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemporalProperties) DeepCopyInto(out *TemporalProperties) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemporalProperties.
func (in *TemporalProperties) DeepCopy() *TemporalProperties {
	if in == nil {
		return nil
	}
	out := new(TemporalProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoomLevelRange) DeepCopyInto(out *ZoomLevelRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoomLevelRange.
func (in *ZoomLevelRange) DeepCopy() *ZoomLevelRange {
	if in == nil {
		return nil
	}
	out := new(ZoomLevelRange)
	in.DeepCopyInto(out)
	return out
}
