---
version: 1.0.0
title: Attributes example
# shortened title, used in breadcrumb path
serviceIdentifier: ATT
abstract: >-
  This example demonstrates serving features (geospatial data) AND attributes (non-spatial data) from a single geopackage.
# just a dummy picture, but you can put an actual thumbnail here
thumbnail: old.png
resources:
  directory: ./examples/resources
keywords:
  - keyword1
  - keyword2
lastUpdated: "2023-09-08T12:00:00Z"
license:
  name: CC0 1.0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.nl
support:
  name: Example Support
  email: support@example.com
  url: https://support.example.com
baseUrl: http://localhost:8080
availableLanguages:
  - nl
  - en
ogcApi:
  # which OGC apis to enable. Possible values: tiles, styles, features, 3dgeovolumes
  features:
    basemap: OSM
    datasources:
      defaultWGS84:
        geopackage:
          local:
            file: ./internal/ogc/features/datasources/geopackage/testdata/attributes.gpkg
            queryTimeout: 5s
    collections:
      - id: roads
        tableName: road
        metadata:
          title: Roads
          description: This is features data (geospatial data)
          lastUpdated: "2030-01-02T12:00:00Z"
          extent:
            srs: EPSG:4326
            bbox: [ "50.2129", "2.52713", "55.7212", "7.37403" ]
            interval: [ "\"1970-01-01T00:00:00Z\"", "null" ]
      - id: road_extras
        tableName: road_extras
        metadata:
          title: Road extras
          description: This is attribute data (non-spatial data)
          lastUpdated: "2030-01-02T12:00:00Z"
