---
version: 1.0.0
resources:
  directory: ./examples/resources
lastUpdated: "2024-10-22T12:00:00Z"
baseUrl: http://localhost:8080
availableLanguages:
  - nl
  - en
database:
  connectionString: "example string"
collections:
  - id: addresses
    metadata:
      title: Addresses
      description: These are example addresses
      extent:
        bbox:
          - 50.2129
          - 2.52713
          - 55.7212
          - 7.37403
  - id: buildings
    metadata:
      title: Buildings
      description: These are example buildings
      extent:
        bbox:
          - 50.2129
          - 2.52713
          - 55.7212
          - 7.37403