/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CollectionsCollectionsInner } from '../models/CollectionsCollectionsInner'
import { Link } from '../models/Link'
import { HttpFile } from '../http/http'

export class Collections {
  'collections': Array<CollectionsCollectionsInner>
  'links': Array<Link> | null

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'collections',
      baseName: 'collections',
      type: 'Array<CollectionsCollectionsInner>',
      format: '',
    },
    {
      name: 'links',
      baseName: 'links',
      type: 'Array<Link>',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return Collections.attributeTypeMap
  }

  public constructor() {}
}
