/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http'

/**
 * JSON schema for exceptions based on RFC 7807
 */
export class Exception {
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  'detail'?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
   */
  'instance'?: string
  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  'status'?: number
  /**
   * A short, human-readable summary of the problem type.
   */
  'title': string
  /**
   * A URI reference that identifies the problem type.
   */
  'type'?: string

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'detail',
      baseName: 'detail',
      type: 'string',
      format: '',
    },
    {
      name: 'instance',
      baseName: 'instance',
      type: 'string',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'number',
      format: '',
    },
    {
      name: 'title',
      baseName: 'title',
      type: 'string',
      format: '',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return Exception.attributeTypeMap
  }

  public constructor() {}
}
