/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpatialExtent } from '../models/SpatialExtent'
import { TemporalExtent } from '../models/TemporalExtent'
import { HttpFile } from '../http/http'

/**
 * The extent of the collection. In the Core only spatial and temporal extents are specified. Extensions may add additional members to represent other  extents, for example, thermal or pressure ranges. It is recommended that the statial extent is expected in CRS84 except if this is not possible.
 */
export class Extent {
  'spatial'?: SpatialExtent
  'temporal'?: TemporalExtent | null

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'spatial',
      baseName: 'spatial',
      type: 'SpatialExtent',
      format: '',
    },
    {
      name: 'temporal',
      baseName: 'temporal',
      type: 'TemporalExtent',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return Extent.attributeTypeMap
  }

  public constructor() {}
}
