/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FeatureJSONFG } from '../models/FeatureJSONFG'
import { Link } from '../models/Link'
import { HttpFile } from '../http/http'

export class FeatureCollectionJSONFG {
  'conformsTo'?: Array<string>
  'coordRefSys'?: string
  'features': Array<FeatureJSONFG>
  'links'?: Array<Link>
  /**
   * The number of elements in the collection.  A server may omit this information in a response, if the information about the number of elements is not known or difficult to compute.  If the value is provided, the value shall be identical to the number of items in the returned array.
   */
  'numberReturned'?: number
  /**
   * This property indicates the time and date when the response was generated.
   */
  'timeStamp'?: Date

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'conformsTo',
      baseName: 'conformsTo',
      type: 'Array<string>',
      format: 'uri',
    },
    {
      name: 'coordRefSys',
      baseName: 'coordRefSys',
      type: 'string',
      format: 'uri',
    },
    {
      name: 'features',
      baseName: 'features',
      type: 'Array<FeatureJSONFG>',
      format: '',
    },
    {
      name: 'links',
      baseName: 'links',
      type: 'Array<Link>',
      format: '',
    },
    {
      name: 'numberReturned',
      baseName: 'numberReturned',
      type: 'number',
      format: '',
    },
    {
      name: 'timeStamp',
      baseName: 'timeStamp',
      type: 'Date',
      format: 'date-time',
    },
  ]

  static getAttributeTypeMap() {
    return FeatureCollectionJSONFG.attributeTypeMap
  }

  public constructor() {}
}
