/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http'

/**
 * @type FeatureGeoJSONId
 * Type
 * @export
 */
export type FeatureGeoJSONId = number | string

/**
 * @type FeatureGeoJSONIdClass
 * @export
 */
export class FeatureGeoJSONIdClass {
  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined
}
