/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeometrycollectionGeoJSON } from '../models/GeometrycollectionGeoJSON'
import { LinestringGeoJSON } from '../models/LinestringGeoJSON'
import { MultilinestringGeoJSON } from '../models/MultilinestringGeoJSON'
import { MultipointGeoJSON } from '../models/MultipointGeoJSON'
import { MultipolygonGeoJSON } from '../models/MultipolygonGeoJSON'
import { PointGeoJSON } from '../models/PointGeoJSON'
import { PolygonGeoJSON } from '../models/PolygonGeoJSON'
import { HttpFile } from '../http/http'

/**
 * @type GeometryGeoJSON
 * Type
 * @export
 */
export type GeometryGeoJSON =
  | GeometrycollectionGeoJSON
  | LinestringGeoJSON
  | MultilinestringGeoJSON
  | MultipointGeoJSON
  | MultipolygonGeoJSON
  | PointGeoJSON
  | PolygonGeoJSON

/**
 * @type GeometryGeoJSONClass
 * @export
 */
export class GeometryGeoJSONClass {
  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined
}
