/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeometryGeoJSON } from '../models/GeometryGeoJSON'
import { HttpFile } from '../http/http'

export class GeometrycollectionGeoJSON {
  'geometries': Array<GeometryGeoJSON>
  'type': GeometrycollectionGeoJSONTypeEnum

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'geometries',
      baseName: 'geometries',
      type: 'Array<GeometryGeoJSON>',
      format: '',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'GeometrycollectionGeoJSONTypeEnum',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return GeometrycollectionGeoJSON.attributeTypeMap
  }

  public constructor() {}
}

export enum GeometrycollectionGeoJSONTypeEnum {
  GeometryCollection = 'GeometryCollection',
}
