/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Link } from '../models/Link'
import { HttpFile } from '../http/http'

/**
 * Reusable object that contains an id to a resource and links where the object is described or a representation retrieved. Typically it is useful for paths like `\\resources` and `\\resources\\{resourceId}`.   `\\resources` will respond an array of id-link listing the `resourceId` and the links to get it. \\collections and \\collections\\{collectionId} is an exception to this pattern. The fact that `links` is an array can be used to advertise the same object representation in different formats.
 */
export class IdLink {
  'id': string
  'links': Array<Link>
  'title'?: string

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: '',
    },
    {
      name: 'links',
      baseName: 'links',
      type: 'Array<Link>',
      format: '',
    },
    {
      name: 'title',
      baseName: 'title',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return IdLink.attributeTypeMap
  }

  public constructor() {}
}
