/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http'

export class PointGeoJSON {
  'coordinates': Array<number>
  'type': PointGeoJSONTypeEnum

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'coordinates',
      baseName: 'coordinates',
      type: 'Array<number>',
      format: '',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'PointGeoJSONTypeEnum',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return PointGeoJSON.attributeTypeMap
  }

  public constructor() {}
}

export enum PointGeoJSONTypeEnum {
  Point = 'Point',
}
