/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http'

export class SearchGeografischGebiedParameter {
  /**
   * The relevance score of the geografisch_gebied collection.
   */
  'relevance'?: number
  /**
   * The version of the geografisch_gebied collection.
   */
  'version': number

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'relevance',
      baseName: 'relevance',
      type: 'number',
      format: 'float',
    },
    {
      name: 'version',
      baseName: 'version',
      type: 'number',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return SearchGeografischGebiedParameter.attributeTypeMap
  }

  public constructor() {}
}
