/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http'

/**
 * The spatial extent of the element in the collection.
 */
export class SpatialExtent {
  /**
   * One or more bounding boxes that describe the spatial extent of the dataset.
   */
  'bbox': Array<Array<number>>
  /**
   * Coordinate reference system of the coordinates in the spatial extent (property `bbox`). The default reference system is WGS 84 longitude/latitude.
   */
  'crs'?: string

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'bbox',
      baseName: 'bbox',
      type: 'Array<Array<number>>',
      format: '',
    },
    {
      name: 'crs',
      baseName: 'crs',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return SpatialExtent.attributeTypeMap
  }

  public constructor() {}
}
