/**
 * PDOK Location API
 * PDOK Location API enables searching for features over multiple datasets
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Trs } from '../models/Trs'
import { HttpFile } from '../http/http'

/**
 * The temporal extent of the element in the collection.
 */
export class TemporalExtent {
  /**
   * One or more time intervals that describe the temporal extent of the dataset. The value `null` is supported and indicates an open time intervall. In the Core only a single time interval is supported. Extensions may support multiple intervals. If multiple intervals are provided, the union of the intervals describes the temporal extent.
   */
  'interval'?: Array<Array<Date | null>> | null
  'trs'?: Trs

  static readonly discriminator: string | undefined = undefined

  static readonly mapping: { [index: string]: string } | undefined = undefined

  static readonly attributeTypeMap: Array<{ name: string; baseName: string; type: string; format: string }> = [
    {
      name: 'interval',
      baseName: 'interval',
      type: 'Array<Array<Date | null>>',
      format: 'date-time',
    },
    {
      name: 'trs',
      baseName: 'trs',
      type: 'Trs',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return TemporalExtent.attributeTypeMap
  }

  public constructor() {}
}
