---
name: lint (docker)
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            Dockerfile
          sparse-checkout-cone-mode: false
      # Pin 3rd party action to a specific version as security best-practice.
      # Version used: https://github.com/hadolint/hadolint-action/releases/tag/v3.3.0
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5
        with:
          dockerfile: Dockerfile
