---
name: lint (docker)
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
          sparse-checkout-cone-mode: false

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
